### PR TITLE
update schema for items stream

### PR DESCRIPTION
**Pull request by kspeer825**
# Description of change
add `item_data.visiblity`to `items` schema
# Manual QA steps
 - Ran corresponding test on separate branch
 
# Risks
 - Low, schema change
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Review by luandy64 — APPROVED** [review]
Looks good to me! I'm assuming the schema is valid JSON

**Comment by luandy64** [comment]
I retriggered the tests to run, I think it just works

**Comment by luandy64** [comment]
The error is `Items in the first set but not the second: 'present_at_location_ids'`. I think we've seen this because the schema is weird. I'm pretty sure it was this field too

**Comment by luandy64** [comment]
Yup, here's the commit https://github.com/singer-io/tap-square/pull/12/commits/48fc0b7db383e253e0b6fb609e8251072579ab43

**Comment by kspeer825** [comment]
These changes were made in another PR and the issues were addressed

**Pull request closed without merging**
